version: "3"
services:
  server:
    image: architecture:0.1
    hostname: localhost
    container_name: app
    ports:
      - 80:8080
    links:
      - pg_db
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=ainur08_A
      - POSTGRES_USER=postgres
      - POSTGRES_DB=architecture
    ports:
      - 5432:5432