<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../css/normalize.css">
    <link rel="stylesheet" href="../css/skeleton.css">
    <link rel="stylesheet" href="../css/sign-in.css">
    <meta charset="UTF-8">
    <title>Sign In</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="three columns">&nbsp;</div>
        <div class="six columns form">
            <h3>Sign in</h3>
            <form method="post">
                <label for="emailInput">Your email</label>
                <input class="u-full-width" type="email" placeholder="example@mailbox.com" id="emailInput">
                <label for="passwordInput">Password</label>
                <input class="u-full-width" type="password" placeholder="********" id="passwordInput">
                <input class="button-primary" type="submit" value="Submit">
            </form>
        </div>
        <div class="three columns">&nbsp;</div>
    </div>
</div>
</body>
</html>
